# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include: 
      - aaa
    exclude:
      - zzz
#- main

pool:
  vmImage: windows-latest



stages:
- stage: approval
  condition: succeeded()
  jobs:
  - deployment: approvalStage
    displayName: approval Web stage
    environment:
      name: testEnv
    strategy:
       runOnce:
         deploy:
          steps:
            - script: echo Hello world


- stage: deploy
  condition: succeeded()
  jobs:
  

  - job:
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
                pip install selenium
                Get-ChildItem -Path C:\SeleniumWebDrivers\ChromeDriver
        condition: succeeded()
      
      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'

      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: |
            from selenium import webdriver
            from selenium.webdriver.chrome.service import Service
      
            # 设置 Chrome WebDriver 的路径
            chrome_driver_path = 'C:\SeleniumWebDrivers\ChromeDriver'
      
            # 创建 Chrome WebDriver 服务
            chrome_service = Service(chrome_driver_path)
            chrome_service.start()
      
            # 创建 Chrome WebDriver 实例
            driver = webdriver.Chrome(service=chrome_service)
      
            # 打开网页
            driver.get("https://www.google.com")
      
            # 关闭浏览器
            driver.quit()
      
            # 停止 Chrome WebDriver 服务
            chrome_service.stop()
